version: "3.11"
services:
  minkult_django:
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    image: minkult_django:v1.0
    environment:
      - PORT=8000
      - POSTGRES=0
      - HOST=postgres_db
    ports:
      - "8000:8000"
    command: sh -c "/app/entrypoint.sh"

  postgres_db:
    image: postgres
    ports:
      - "4321:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: